/**
 * Janbhasha Design System Theme Tokens
 * Based on Material 3 Modern-Tactile Design Specification (janbhasha_design_system/DESIGN.md)
 */

export const JanbhashaTheme = {
  colors: {
    // Official Material 3 Design Tokens
    surface: '#fbf9f9',
    surfaceDim: '#dbdad9',
    surfaceBright: '#fbf9f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f5f3f3',
    surfaceContainer: '#efeded',
    surfaceContainerHigh: '#e9e8e7',
    surfaceContainerHighest: '#e3e2e2',
    onSurface: '#1b1c1c',
    onSurfaceVariant: '#40493d',
    inverseSurface: '#303031',
    inverseOnSurface: '#f2f0f0',
    outline: '#707a6c',
    outlineVariant: '#bfcaba',
    surfaceTint: '#1b6d24',
    primary: '#0d631b',
    onPrimary: '#ffffff',
    primaryContainer: '#2e7d32',
    onPrimaryContainer: '#cbffc2',
    inversePrimary: '#88d982',
    secondary: '#875200',
    onSecondary: '#ffffff',
    secondaryContainer: '#f89c00',
    onSecondaryContainer: '#623a00',
    tertiary: '#00598f',
    onTertiary: '#ffffff',
    tertiaryContainer: '#0072b6',
    onTertiaryContainer: '#e9f2ff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onConsumerError: '#93000a',
    primaryFixed: '#a3f69c',
    primaryFixedDim: '#88d982',
    secondaryFixed: '#ffddba',
    secondaryFixedDim: '#ffb865',
    tertiaryFixed: '#cfe5ff',
    tertiaryFixedDim: '#99cbff',
    background: '#fbf9f9',
    onBackground: '#1b1c1c',

    // Backward-Compatible Semantic Aliases
    creamBg: '#fbf9f9',
    creamBgLight: '#ffffff',
    white: '#ffffff',
    deepGreen: '#0d631b',
    deepGreenHover: '#0a4b14',
    primaryGreen: '#0d631b',
    leafGreen: '#2e7d32',
    lightGreenBg: '#e9f5eb',
    mintTag: '#cbffc2',
    warmOrange: '#875200',
    warmOrangeLight: '#fff3ed',
    goldAmber: '#875200',
    goldAmberLight: '#ffddba',
    charcoalText: '#1b1c1c',
    mutedText: '#40493d',
    lightText: '#707a6c',
    cardBorder: '#bfcaba',
    subtleDivider: '#efeded',
    errorRed: '#ba1a1a',
    errorRedBg: '#ffdad6',
    audioPulse: '#2e7d32',
    shadowColor: '#1b1c1c',
  },
  fonts: {
    olChiki: 'NotoSansOlChiki-Regular',
    olChikiBold: 'NotoSansOlChiki-Bold',
    primary: 'Be Vietnam Pro',
  },
  borderRadius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 24, // High circularity standard containers
    full: 9999, // Pill shaped interactive buttons
  },
  spacing: {
    base: 8,
    xs: 4,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    gutter: 16,
    marginMobile: 20,
    marginDesktop: 64,
  },
};

