export const JanbhashaTheme = {
  colors: {
    creamBg: '#FAF7F2',
    creamBgLight: '#FFFDF9',
    white: '#FFFFFF',
    deepGreen: '#1B4D3E',
    deepGreenHover: '#143C30',
    primaryGreen: '#246B54',
    leafGreen: '#2E7D32',
    lightGreenBg: '#E8F5E9',
    mintTag: '#E0F2E9',
    warmOrange: '#E06D3B',
    warmOrangeLight: '#FFF3ED',
    goldAmber: '#D97706',
    goldAmberLight: '#FEF3C7',
    charcoalText: '#1E293B',
    mutedText: '#64748B',
    lightText: '#94A3B8',
    cardBorder: '#EBE5DC',
    subtleDivider: '#F0EBE1',
    errorRed: '#DC2626',
    errorRedBg: '#FEE2E2',
    audioPulse: '#10B981',
    shadowColor: '#1A1918',
  },
  fonts: {
    olChiki: 'NotoSansOlChiki-Regular',
    olChikiBold: 'NotoSansOlChiki-Bold',
  },
  borderRadius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 26,
    full: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 14,
    lg: 20,
    xl: 28,
  },
};
