// Auto-generated offline asset registry for Janbhasha

export const avatar_teacher_find_classroom_1 = require('./avatar_teacher_find_classroom_1.png'); // A professional portrait of an Indian male teacher in his 40s (53 KB)
export const asset_splash_screen_2 = require('./asset_splash_screen_2.png'); // background (70 KB)
export const asset_splash_screen_material_3_3 = require('./asset_splash_screen_material_3_3.png'); // background (85 KB)
export const asset_start_network_4 = require('./asset_start_network_4.png'); // A warm, engaging flat-vector illustration showing a glowing  (37 KB)
export const avatar_teacher_connecting_5 = require('./avatar_teacher_connecting_5.png'); // A professional headshot of a welcoming, experienced Indian m (54 KB)
export const avatar_student_discovering_students_6 = require('./avatar_student_discovering_students_6.png'); // A small, soft-lit avatar illustration of a student in a warm (24 KB)
export const avatar_student_discovering_students_7 = require('./avatar_student_discovering_students_7.png'); // A small, soft-lit avatar illustration of a student in a warm (20 KB)
export const avatar_student_discovering_students_8 = require('./avatar_student_discovering_students_8.png'); // A headshot illustration of an Indian student smiling, drawn  (33 KB)
export const asset_welcome_screen_9 = require('./asset_welcome_screen_9.png'); // background (32 KB)
export const backdrop_village_10 = require('./backdrop_village_10.png'); // Rural Village School Backdrop (919 KB)
export const avatar_teacher_joined_successfully_11 = require('./avatar_teacher_joined_successfully_11.png'); // A culturally appropriate, welcoming profile illustration of  (41 KB)
export const avatar_student_student_dashboard_12 = require('./avatar_student_student_dashboard_12.png'); // A smiling young student with a backpack, portrait style, sof (39 KB)
export const avatar_student_student_dashboard_13 = require('./avatar_student_student_dashboard_13.png'); // A smiling young student with a backpack, portrait style, sof (60 KB)
export const illustration_math_14 = require('./illustration_math_14.png'); // A stylized, colorful illustration representing mathematics l (33 KB)
export const illustration_language_15 = require('./illustration_language_15.png'); // A warm, engaging illustration representing language learning (41 KB)
export const illustration_science_16 = require('./illustration_science_16.png'); // An inspiring illustration for science learning. Features a m (40 KB)
export const avatar_student_learning_path_17 = require('./avatar_student_learning_path_17.png'); // A portrait photo of a young smiling student, warm lighting,  (39 KB)
export const backdrop_village_18 = require('./backdrop_village_18.png'); // Village Illustration (77 KB)
export const avatar_teacher_teacher_dashboard_1_19 = require('./avatar_teacher_teacher_dashboard_1_19.png'); // A small circular avatar portrait of an Indian male school te (45 KB)
export const avatar_teacher_teacher_dashboard_1_20 = require('./avatar_teacher_teacher_dashboard_1_20.png'); // A high-quality, professional headshot of an Indian school te (25 KB)
export const asset_teacher_dashboard_1_21 = require('./asset_teacher_dashboard_1_21.png'); // background (52 KB)
export const avatar_teacher_teacher_dashboard_2_22 = require('./avatar_teacher_teacher_dashboard_2_22.png'); // Warm portrait photograph of an Indian primary school teacher (49 KB)
export const avatar_teacher_classroom_management_23 = require('./avatar_teacher_classroom_management_23.png'); // Teacher or Student Profile (35 KB)
export const qr_classroom_24 = require('./qr_classroom_24.png'); // A highly detailed, crisp, black and white QR code image. The (26 KB)
export const avatar_teacher_live_classroom_25 = require('./avatar_teacher_live_classroom_25.png'); // A small, circular avatar portrait of a mature female teacher (60 KB)
export const asset_student_translation_26 = require('./asset_student_translation_26.png'); // User profile photo (54 KB)
export const avatar_student_omr_result_27 = require('./avatar_student_omr_result_27.png'); // A small circular avatar placeholder image showing a smiling  (42 KB)
export const avatar_student_omr_result_28 = require('./avatar_student_omr_result_28.png'); // A portrait of a young Indian student wearing a clean white s (38 KB)
export const asset_admin_dashboard_29 = require('./asset_admin_dashboard_29.png'); // User profile photo (17 KB)
export const asset_language_packs_30 = require('./asset_language_packs_30.png'); // User profile photo (41 KB)
export const asset_broadcast_lesson_31 = require('./asset_broadcast_lesson_31.png'); // A stylized, flat illustration of geometric shapes representi (16 KB)
export const avatar_teacher_class_performance_analytics_32 = require('./avatar_teacher_class_performance_analytics_32.png'); // A small circular profile picture of an Indian school teacher (51 KB)
export const asset_database_backup_33 = require('./asset_database_backup_33.png'); // Database server visualization (26 KB)
export const asset_guided_offline_broadcast_34 = require('./asset_guided_offline_broadcast_34.png'); // A brightly lit, high-resolution educational infographic show (37 KB)
export const avatar_teacher_guided_offline_broadcast_35 = require('./avatar_teacher_guided_offline_broadcast_35.png'); // A warm, engaging headshot of an Indian school teacher wearin (39 KB)
export const asset_language_management_36 = require('./asset_language_management_36.png'); // background (190 KB)
export const asset_school_management_37 = require('./asset_school_management_37.png'); // Admin User Profile (39 KB)
export const asset_school_management_38 = require('./asset_school_management_38.png'); // System Administrator (52 KB)
export const asset_teacher_verification_39 = require('./asset_teacher_verification_39.png'); // A small, circular avatar portrait of an Indian administrativ (48 KB)
export const asset_teacher_verification_40 = require('./asset_teacher_verification_40.png'); // System Administrator (57 KB)
export const avatar_teacher_teacher_verification_41 = require('./avatar_teacher_teacher_verification_41.png'); // A warm, professional portrait photo of a young female Indian (46 KB)
export const avatar_teacher_teacher_verification_42 = require('./avatar_teacher_teacher_verification_42.png'); // A portrait of a male Indian educator in his 40s wearing a cr (39 KB)
export const avatar_teacher_teacher_verification_43 = require('./avatar_teacher_teacher_verification_43.png'); // A portrait of a young male teacher from a rural Indian distr (54 KB)
export const asset_weak_topics_detail_44 = require('./asset_weak_topics_detail_44.png'); // background (31 KB)
export const village_school_banyan = require('./village_school_banyan.png');
export const splash_screen_mockup = require('./splash_screen_mockup.png');
export const welcome_backdrop = require('./welcome_backdrop.png');
export const language_selection_mockup = require('./language_selection_mockup.png');
export const role_selection_mockup = require('./role_selection_mockup.png');
export const student_dashboard_mockup = require('./student_dashboard_mockup.png');
export const story_time_illustration = require('./story_time_illustration.png');
export const teacher_dashboard_mockup = require('./teacher_dashboard_mockup.png');
export const live_classroom_mockup = require('./live_classroom_mockup.png');
export const student_translation_mockup = require('./student_translation_mockup.png');
export const broadcast_lesson_mockup = require('./broadcast_lesson_mockup.png');
export const student_ask_ai_mockup = require('./student_ask_ai_mockup.png');
