// ============================================================
// ModelManifest.cpp
// ============================================================
#include "ModelManifest.h"
#include "../errors/JanbhashaErrors.h"

#include <fstream>
#include <sstream>
#include <iomanip>
#include <array>
#include <algorithm>

// Minimal JSON parsing without external dependencies (nlohmann/json
// is NOT assumed in the NDK build). Uses a hand-rolled field extractor
// that is intentionally simple — the manifest JSON must be well-formed
// and generated by the Python download script.
//
// If your project already uses nlohmann/json (via find_package), swap
// the parse block below with nlohmann equivalents.

// SHA-256 implementation — RFC 6234 reference implementation (public domain)
#include <cstring>

namespace janbhasha {

// ---- Minimal SHA-256 ------------------------------------------------
namespace sha256_impl {

static const uint32_t K[64] = {
    0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,
    0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,
    0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,
    0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,
    0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,
    0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
    0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,
    0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,
    0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
    0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,
    0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
};

#define ROTR32(x,n) (((x)>>(n))|((x)<<(32-(n))))
#define CH(x,y,z) (((x)&(y))^(~(x)&(z)))
#define MAJ(x,y,z) (((x)&(y))^((x)&(z))^((y)&(z)))
#define EP0(x) (ROTR32(x,2)^ROTR32(x,13)^ROTR32(x,22))
#define EP1(x) (ROTR32(x,6)^ROTR32(x,11)^ROTR32(x,25))
#define SIG0(x) (ROTR32(x,7)^ROTR32(x,18)^((x)>>3))
#define SIG1(x) (ROTR32(x,17)^ROTR32(x,19)^((x)>>10))

std::string compute(const uint8_t* data, size_t len) {
    uint32_t h[8] = {
        0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,
        0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19
    };

    // Pad
    std::vector<uint8_t> msg(data, data + len);
    msg.push_back(0x80);
    while (msg.size() % 64 != 56) msg.push_back(0x00);
    uint64_t bit_len = static_cast<uint64_t>(len) * 8;
    for (int i = 7; i >= 0; --i)
        msg.push_back(static_cast<uint8_t>((bit_len >> (i * 8)) & 0xFF));

    for (size_t i = 0; i < msg.size(); i += 64) {
        uint32_t w[64];
        for (int j = 0; j < 16; ++j)
            w[j] = (msg[i+j*4]<<24)|(msg[i+j*4+1]<<16)|(msg[i+j*4+2]<<8)|msg[i+j*4+3];
        for (int j = 16; j < 64; ++j)
            w[j] = SIG1(w[j-2]) + w[j-7] + SIG0(w[j-15]) + w[j-16];

        uint32_t a=h[0],b=h[1],c=h[2],d=h[3],e=h[4],f=h[5],g=h[6],hh=h[7];
        for (int j = 0; j < 64; ++j) {
            uint32_t t1 = hh + EP1(e) + CH(e,f,g) + K[j] + w[j];
            uint32_t t2 = EP0(a) + MAJ(a,b,c);
            hh=g; g=f; f=e; e=d+t1; d=c; c=b; b=a; a=t1+t2;
        }
        h[0]+=a; h[1]+=b; h[2]+=c; h[3]+=d;
        h[4]+=e; h[5]+=f; h[6]+=g; h[7]+=hh;
    }

    std::ostringstream oss;
    oss << std::hex << std::setfill('0');
    for (int i = 0; i < 8; ++i) oss << std::setw(8) << h[i];
    return oss.str();
}

} // namespace sha256_impl

// ---- Tiny JSON field extractor -------------------------------------
// Only supports flat string, integer, and boolean fields inside an
// array of objects. Good enough for model_manifest.json.

static std::string extractStringField(const std::string& obj, const std::string& key) {
    std::string needle = "\"" + key + "\"";
    auto pos = obj.find(needle);
    if (pos == std::string::npos) return {};
    auto colon = obj.find(':', pos);
    if (colon == std::string::npos) return {};
    auto start = obj.find('"', colon);
    if (start == std::string::npos) return {};
    auto end = obj.find('"', start + 1);
    if (end == std::string::npos) return {};
    return obj.substr(start + 1, end - start - 1);
}

static uint64_t extractUint64Field(const std::string& obj, const std::string& key) {
    std::string needle = "\"" + key + "\"";
    auto pos = obj.find(needle);
    if (pos == std::string::npos) return 0;
    auto colon = obj.find(':', pos);
    if (colon == std::string::npos) return 0;
    size_t i = colon + 1;
    while (i < obj.size() && (obj[i] == ' ' || obj[i] == '\t')) ++i;
    uint64_t val = 0;
    while (i < obj.size() && std::isdigit(obj[i])) val = val * 10 + (obj[i++] - '0');
    return val;
}

static bool extractBoolField(const std::string& obj, const std::string& key) {
    std::string needle = "\"" + key + "\"";
    auto pos = obj.find(needle);
    if (pos == std::string::npos) return false;
    auto colon = obj.find(':', pos);
    if (colon == std::string::npos) return false;
    auto t = obj.find("true", colon);
    auto comma = obj.find(',', colon);
    return (t != std::string::npos && (comma == std::string::npos || t < comma));
}

// ---- ModelManifest implementation ----------------------------------

ModelManifest::ModelManifest(const std::string& manifestPath)
    : manifestPath_(manifestPath) {}

bool ModelManifest::load() {
    std::ifstream f(manifestPath_);
    throwIf(!f.is_open(), ErrorCode::MODEL_MANIFEST_INVALID,
            "Cannot open manifest: " + manifestPath_);

    std::ostringstream ss;
    ss << f.rdbuf();
    std::string json = ss.str();

    // Find the "models" array
    auto models_pos = json.find("\"models\"");
    throwIf(models_pos == std::string::npos, ErrorCode::MODEL_MANIFEST_INVALID,
            "manifest missing 'models' key");

    auto arr_start = json.find('[', models_pos);
    auto arr_end   = json.rfind(']');
    throwIf(arr_start == std::string::npos || arr_end == std::string::npos,
            ErrorCode::MODEL_MANIFEST_INVALID, "manifest 'models' array malformed");

    std::string arr = json.substr(arr_start + 1, arr_end - arr_start - 1);

    // Split into individual objects by counting braces
    size_t i = 0;
    while (i < arr.size()) {
        while (i < arr.size() && arr[i] != '{') ++i;
        if (i >= arr.size()) break;
        int depth = 0;
        size_t obj_start = i;
        while (i < arr.size()) {
            if (arr[i] == '{') ++depth;
            else if (arr[i] == '}') { --depth; if (depth == 0) { ++i; break; } }
            ++i;
        }
        std::string obj = arr.substr(obj_start, i - obj_start);

        ModelEntry entry;
        entry.id             = extractStringField(obj, "id");
        entry.displayName    = extractStringField(obj, "displayName");
        entry.modelType      = extractStringField(obj, "modelType");
        entry.localPath      = extractStringField(obj, "localPath");
        entry.sha256         = extractStringField(obj, "sha256");
        entry.fileSizeBytes  = extractUint64Field(obj, "fileSizeBytes");
        entry.estimatedRamMb = static_cast<uint32_t>(extractUint64Field(obj, "estimatedRamMb"));
        entry.quantization   = extractStringField(obj, "quantization");
        entry.required       = extractBoolField(obj, "required");

        if (!entry.id.empty()) entries_.push_back(std::move(entry));
    }

    loaded_ = true;
    return true;
}

std::optional<ModelEntry> ModelManifest::find(const std::string& modelId) const {
    for (const auto& e : entries_) {
        if (e.id == modelId) return e;
    }
    return std::nullopt;
}

bool ModelManifest::verifyChecksum(const std::string& modelId) const {
    auto entry = find(modelId);
    throwIf(!entry.has_value(), ErrorCode::MODEL_NOT_FOUND,
            "Model not in manifest: " + modelId);

    if (entry->sha256.empty()) return true; // no checksum → skip

    std::ifstream f(entry->localPath, std::ios::binary);
    throwIf(!f.is_open(), ErrorCode::MODEL_NOT_FOUND,
            "Model file not found: " + entry->localPath);

    std::vector<uint8_t> buf(std::istreambuf_iterator<char>(f), {});
    std::string computed = sha256_impl::compute(buf.data(), buf.size());

    std::string expected = entry->sha256;
    std::transform(expected.begin(), expected.end(), expected.begin(), ::tolower);

    if (computed != expected) {
        throw JanbhashaError(ErrorCode::MODEL_CHECKSUM_MISMATCH,
            "SHA256 mismatch for " + modelId + ": expected=" + expected + " got=" + computed);
    }
    return true;
}

std::string ModelManifest::computeSha256(const std::string& filePath) {
    std::ifstream f(filePath, std::ios::binary);
    if (!f.is_open()) return {};
    std::vector<uint8_t> buf(std::istreambuf_iterator<char>(f), {});
    return sha256_impl::compute(buf.data(), buf.size());
}

} // namespace janbhasha
